### ISSUE TITLE
space after todo box

### ISSUE THREAD

**Issue by aboutjax** [chrisgreeff/cookbook#16]
@chrisgreeff currently there's no space between the todo box and the note.

it would also be nice if the lines between todo's can be a bit wider, see image.
![screen shot 2013-10-31 at 6 48 30 pm](https://f.cloud.github.com/assets/5724081/1443715/237f990c-41f0-11e3-8637-718316f33ebf.png)

**Comment by chrisgreeff** [comment]
I'm not sure what you're referring to... could you take a screen shot or something to help explain?
